### ISSUE TITLE
token undefined

### ISSUE THREAD

**Issue by Xeonxoo99** [ddoddiworld/miniproject9-fe#3]
![image](https://github.com/ddoddiworld/miniproject9-fe/assets/130985864/068ec524-043b-42c5-b342-710aeff13835)

token을 받아온 뒤 검사모드에서 undefined로 표기가 되어 수정이 필요합니다.

**Comment by ddoddiworld** [comment]
우선 기존에 local Storage에 저장하는 방법에서 cookie로 토큰을 받는 방식으로 변경하였습니다.

![image](https://github.com/ddoddiworld/miniproject9-fe/assets/93027502/a51527a7-cedc-435e-a1b6-425a9635328f)

그리고 토큰에 담는 값을 아래와 같이 수정하였습니다.

![image](https://github.com/ddoddiworld/miniproject9-fe/assets/93027502/8c5d141f-5e49-4e43-ad48-f4046ce44478)

그 결과, 정상적으로 쿠키에 토큰이 들어가 있는 것을 확인할 수 있었습니다.

![image](https://github.com/ddoddiworld/miniproject9-fe/assets/93027502/c70390a7-000a-4b53-9ed3-c152467470f7)
