### ISSUE TITLE
token 값 오류

### ISSUE THREAD

**Issue by Xeonxoo99** [ddoddiworld/miniproject9-fe#5]
![image](https://github.com/ddoddiworld/miniproject9-fe/assets/130985864/0d498c1a-72d3-4d8f-8374-c2f973b39c90)

token 값이 토큰 문자열이 아닌 'token'으로 들어와 확인 필요합니다.

**Comment by ddoddiworld** [comment]
2일 동안 로그인 토큰 이슈를 붙들고 있었는데 9조 맴버들 모두 정말 고생 많으셨습니다! 결국 해결했네요! 만세👏🏻!
