### ISSUE TITLE
덕담 작성 불가능 - 401, 412 에러 발생

### ISSUE THREAD

**Issue by ddoddiworld** [ddoddiworld/miniproject9-fe#6]

**Comment by ddoddiworld** [comment]
![image](https://github.com/ddoddiworld/miniproject9-fe/assets/93027502/8c300a3d-a90a-4a00-b396-da721fd3ae76)

**[401 에러]**
문제 원인 : 토큰 값을 서버에서 찾지 못하고 있었음.
문제 해결 : accessToken에서 refreshToken으로 변경했더니 401 에러는 해결 되었음.

**[412 에러]**
문제 원인 : 본인이 본인에게 덕담을 작성해서 발생한 에러였음
문제 해결 : 다른 사람의 페이지로 넘어가서 덕담을 작성하니 정상적으로 덕담이 등록되었음

**Comment by Xeonxoo99** [comment]
확인했습니다!
